# Generated by Django 3.0.6 on 2020-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('api_key', models.CharField(max_length=256)),
                ('api_secret', models.CharField(max_length=256)),
            ],
        ),
    ]
