# Generated by Django 3.0.6 on 2020-05-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=8)),
                ('volume', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('Buy', 'Buy this order'), ('Sell', 'Sell this order')], max_length=9)),
                ('price', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Account')),
            ],
        ),
    ]
